### ISSUE TITLE
NOTE

### ISSUE THREAD

**Issue by xadadev** [StarlaneStudios/vscode-comment-anchors#101]
Uncaught ReferenceError: NOTE is not defined giving the error when using NOTE. NOTE supposed not to be executed as a js variable
![Screenshot](https://user-images.githubusercontent.com/21056859/97916028-38208800-1d74-11eb-886e-8368e1ceea69.png)

.

**Comment by JordanDi123** [comment]
Could you provide more information on this problem? Notes seem to work just fine for me.

**Comment by macjuul** [comment]
Closing this issue as no further information was provided
