### ISSUE TITLE
LINK path#someId to ANCHOR[id=someId] does not match

### ISSUE THREAD

**Issue by sukiasian** [StarlaneStudios/vscode-comment-anchors#102]
I have **3** LINKs to ANCHORs:
1)
```
// LINK ./links/file1.js#file1 
// ANCHOR[id=file1]
```
2) 
```
// LINK ./path/file2.js#file2
// ANCHOR[id=file2]

```
3) 
```
// LINK ./path/file3.js#file3
// ANCHOR[id=file3]
```

The file structure is like that: 
Imagine I have links/ directory with 3 files (file1.js, file2.js and file3.js) for LINKs and anchors/ directory with 3 files (file1, file2, file3) for anchors. 

So when I click on    LINK ./path/file1.js#file1, I get to ANCHOR[id=file3], although I had to get to ANCHOR[id=file1].

Tried to restart both VSCode and PC, tried to exclude unused files - does not work :/

VSCode version: 1.51.1

**Comment by JordanDi123** [comment]
Can this issue be reproduced on 1.9.3? We made some changes to link anchors (#120) that could have resolved this issue.

Thanks for the report nonetheless! 👍
