### ISSUE TITLE
Broken link anchors break others

### ISSUE THREAD

**Issue by dolsem** [StarlaneStudios/vscode-comment-anchors#103]
The second link anchor works on its own, but when the first (invalid) link anchor is present, the second stops working as well.

![Screen Shot 2020-12-22 at 12 56 05 PM](https://user-images.githubusercontent.com/14323955/102932470-3494ad80-4455-11eb-815f-6f18607df132.png)

**Comment by macjuul** [comment]
Closing as this issue should be fixed in the current version
