### ISSUE TITLE
Lower case tags dont work

### ISSUE THREAD

**Issue by demimurych** [StarlaneStudios/vscode-comment-anchors#113]
Trouble [in this code](https://github.com/ExodiusStudios/vscode-comment-anchors/blob/099ea64289774f1affcfd384b0ca68c3094c9b6a/src/anchorEngine.ts#L390)

```typeScript
      config.tags.list.forEach((tag: TagEntry) => {
 ```
      
**Wrong uppercase [in this line](https://github.com/ExodiusStudios/vscode-comment-anchors/blob/099ea64289774f1affcfd384b0ca68c3094c9b6a/src/anchorEngine.ts#L391)**
```typeScript
        const def = this.tags.get(tag.tag.toUpperCase()) || {};
        const opts = { ...def, ...tag };

        // Skip disabled default tags
        if (tag.enabled === false) {
 ```
**Wrong uppercase [in this line](https://github.com/ExodiusStudios/vscode-comment-anchors/blob/099ea64289774f1affcfd384b0ca68c3094c9b6a/src/anchorEngine.ts#L396)**
```typeScript
          this.tags.delete(tag.tag.toUpperCase());
          return;
        }

        // Fix legacy isRegion tag
        if (opts.isRegion) {
          opts.behavior = "region";
        }
```
**Wrong uppercase[ in this line](https://github.com/ExodiusStudios/vscode-comment-anchors/blob/099ea64289774f1affcfd384b0ca68c3094c9b6a/src/anchorEngine.ts#L405)**
```typeScript
        this.tags.set(tag.tag.toUpperCase(), opts);
      });
```

**Comment by macjuul** [comment]
Hello!

Since making changes to the anchor parsing system is risky and I currently don't have enough time to properly test it I'll have to keep this feature on hold for now.

However, have you tried setting the configuration option `commentAnchors.tags.matchCase` to false? This might be a good temporary solution to allow lowercase anchors to work.

**Comment by demimurych** [comment]
Thank you very much for your answer.
