### ISSUE TITLE
Exclude custom tags from "File Anchors" sidebar

### ISSUE THREAD

**Issue by StephanReti** [StarlaneStudios/vscode-comment-anchors#115]
Is there a way to completely exclude some custom tags from the sidebar?

I am trying to get a highlighted comment, but I don't want $-tags to clutter the "File Anchors" sidebar. 

This is what I have so far:

<img width="838" alt="Multi-define comments" src="https://user-images.githubusercontent.com/54271246/115789912-2d12f000-a3c6-11eb-909b-6cfb25982f9e.png">

Currently my settings.json looks like this:

```.json
"commentAnchors.tags.displayLineNumber": false,
"commentAnchors.tags.displayInSidebar": false,
"commentAnchors.tags.list": [
  {
    "tag": "MARK",
    "iconColor": "#E5E059",
    "highlightColor": "#E5E059",
    "scope": "file"
  },
  {
    "tag": "$",
    "iconColor": "#1E1E1E",
    "highlightColor": "#9F9F9F",
    "scope": "file",
    "styleComment": true
  },
]
```

Making the icon color = the background color is not elegant, but I think it helps with sidebar and code readability.

**Comment by macjuul** [comment]
Apologies for my late response.

This can be achieved by setting the scope of your tag to `hidden`, which will hide it from the sidebar.

**Comment by StephanReti** [comment]
Thanks, it works like a charm!

Result:

<img width="996" alt="VSCode comment anchors" src="https://user-images.githubusercontent.com/54271246/151676842-9301cce5-503d-47d5-b026-0dc6c182f0f3.png">

Settings.json:
```json
{
  "commentAnchors.tags.displayLineNumber": false,
  "commentAnchors.tags.displayInSidebar": false,
  "commentAnchors.tags.list": [
    {
      "tag": "MARK",
      "iconColor": "#E5E059",
      "highlightColor": "#E5E059",
      "scope": "file"
    },
    {
      "tag": "$",
      "iconColor": "#1E1E1E",
      "highlightColor": "#9F9F9F",
      "scope": "hidden",
      "styleComment": true
    },
  ]
}
```
