### ISSUE TITLE
Suggestion: color the comment before the tag

### ISSUE THREAD

**Issue by firas724** [StarlaneStudios/vscode-comment-anchors#132]
Hello, thank you for the great extension. I think the visibility of the anchors would be much greater if the comment before the tag is also colored by the color of the tag. I write in python and sometimes I put several hashtags to highlight a note (make it stand out more) and if those are colored too it would be very helpful. (similar to the better comment extension)

**Comment by Maelep** [comment]
I'm also interested by this feature but not by default, I would prefer a parameter like `"styleSlash": true`.

**Comment by macjuul** [comment]
Duplicate of #31 which has just been implemented and will be available in the next release.
