### ISSUE TITLE
Problems with Powershell documentation comments

### ISSUE THREAD

**Issue by Callidus2000** [StarlaneStudios/vscode-comment-anchors#133]
Hi,
I'm using vscode for PowerShell development. Within PowerShell comments are used to document functions and scripts.

As an shortened example:

```powershell
<#
.SYNOPSIS
    Get names of local printers from the specified computer

.NOTES
    This PowerShell script was developed ....

.LINK
    https://github.com/scriptrunner/ActionPacks/tree/master/WinPrintManagement/_QUERY_

.Parameter ComputerName
    Specifies the name of the computer from which to retrieve the printer information
#>
```

The extension identifies the .NOTES as a NOTE Anchor and the .LINK as a LINK anchor.

Is it possible to deactivate this behavior? Otherwise the extension is useless for powershell...

**Comment by danilort** [comment]
I have a similar problem, and I suggested this:
https://github.com/StarlaneStudios/vscode-comment-anchors/issues/138

**Comment by macjuul** [comment]
Hello and thanks for your issue!

Since this specific issue has received lots of attention recently, any further discussion on the topic will be consolidated into #116
