### ISSUE TITLE
epic anchors only work at top level

### ISSUE THREAD

**Issue by dbramblett** [StarlaneStudios/vscode-comment-anchors#134]
I can only add an anchor with a epic attribute at the top most level in a document. If I attempt to put it under even one layer of a region anchor pair, it goes unrecognized.

The following example in LUA works.

```
-- SECTION
-- !SECTION
-- FIXME[epic=Test]
```
This does not

```
-- SECTION
-- FIXME[epic=Test]
-- !SECTION
```

**Comment by macjuul** [comment]
This issue will be fixed in the next release

**Comment by dbwodlf3** [comment]
yet fixed...
