### ISSUE TITLE
Anchor appears when keyword is not inside a comment, but inside a TS Enum

### ISSUE THREAD

**Issue by rodrigoaddor** [StarlaneStudios/vscode-comment-anchors#136]
Hello! Not sure if this is intended or not, but I'm getting comment anchors on Typescript enum keys.

Example: 
```typescript
enum Test {
  TODO = 'todo',
  NOTE = 'note'
}
```

![image](https://user-images.githubusercontent.com/5903458/144461429-3efcc9c3-a0c3-40f8-a39f-92a161353dba.png)

I'm not sure if the anchors are supposed to appear in any appearances of the keywords, but although it is not something that breaks some functionality or such, it would be good to have a setting so that anchors only appear inside comments.

Cheers!

**Comment by danilort** [comment]
I suggested this change: https://github.com/StarlaneStudios/vscode-comment-anchors/issues/138

**Comment by macjuul** [comment]
Hello and thanks for your issue!

Since this specific issue has received lots of attention recently, any further discussion on the topic will be consolidated into #116
