### ISSUE TITLE
[Feature request] Less false anchors

### ISSUE THREAD

**Issue by danilort** [StarlaneStudios/vscode-comment-anchors#138]
This is a beautiful extension, but there is a problem: many false anchors are found.

![immagine](https://user-images.githubusercontent.com/16148184/146681872-0e9493b1-cb6a-431a-b1c5-f719e6001e32.png)

You should limit the characters that are allowed around the text string.
It would be very useful to be able to define the allowed characters.

### matchBefore

```
"commentAnchors.tags.matchBefore": [
    " ",
    "//"
],
```

```
// ANCHOR this is an anchor
//ANCHOR this is an anchor
// NEXT-ANCHOR this is not an anchor
//anytext "ANCHOR" this is not an anchor
// AAA/ANCHOR/BBB this is not an anchor
```

### matchAfter
```
"commentAnchors.tags.matchAfter": [
    " ",
    ":"
],
```

```
//ANCHOR this is an anchor
//ANCHOR: this is an anchor
//ANCHOR_TYPE this is not an anchor
//ANCHOR.TYPE this is not an anchor
//ANCHOR123 this is not an anchor
```

## My config
CommentAnchors v1.9.6
VSCODE v1.63.2
OS: Windows 10

**Comment by macjuul** [comment]
Hello and thanks for your issue!

Since this specific issue has received lots of attention recently, any further discussion on the topic will be consolidated into #116
