### ISSUE TITLE
Folding by Sections

### ISSUE THREAD

**Issue by lucas-abbate** [StarlaneStudios/vscode-comment-anchors#144]
Hi! I've started using your extension and I'm really enjoying it.
I would love that, by using the SECTION tag, it would make it possible to fold the code within the section. By default it is possible to fold blocks of code (like for loops and ifs), but when using it with Anchor, the comments should be inside the block for them to be folded, and I think that makes it look pretty loaded when everything is folded
![image](https://user-images.githubusercontent.com/56030917/153035394-f86a2a24-b9c6-47e0-bbcf-585717d904fd.png)
Hope you can follow my suggestion (and sorry for my bad english)
Thanks!

PS: I've tried to follow the guidelines to talk about my suggestion on the Discord server, but the invite on CONTRIBUTING.md is broken. Sorry for not getting feedback on the server

**Comment by macjuul** [comment]
Sorry for the late response. Section folding is a feature we used to offer however it caused major issues for multiple languages, hence it was removed (#52). 

If a better solution to section folding can be found, a PR is always welcome.
