### ISSUE TITLE
Possible to customize the link anchor string and appearance?

### ISSUE THREAD

**Issue by carloscadux** [StarlaneStudios/vscode-comment-anchors#146]
Hi,

a) Although I'm a fan of the link anchor, I'd like to change its default string (e.g. to 'connect').
b) Also, the default color is 'green', but I'd like 'purple'.

Are those customizations possible to achieve?

Thanks!

![image](https://user-images.githubusercontent.com/7339389/157074609-376637c3-12ae-4759-8020-b6b902b1d506.png)

**Comment by macjuul** [comment]
Sorry for the long delay, this is possible by configuring the default `LINK` tag by setting `enabled` to `false`.
