### ISSUE TITLE
Feature Request: Json Extension Settings: Use a dictionary key value for each anchor.

### ISSUE THREAD

**Issue by dbramblett** [StarlaneStudios/vscode-comment-anchors#152]
If the name of an anchor was defined via a key rather than a property within the anchor declaration in the settings JSON, it would be possible to fold it AND see which anchor it is.

Specific use case, I have a lot of anchors defined and if I could fold them so only the name of the anchor was visible, I could get a lot more of them on screen at once, which in turn would allow me to compare two anchors at opposite ends of the list more easily.

**Comment by macjuul** [comment]
I've faced similar frustrations before so I've gone ahead and updated the way anchors are configured. The old array-based syntax is still accepted as well but has been marked as deprecated.

![image](https://user-images.githubusercontent.com/7606171/194713639-3507968d-7189-425f-86fb-277dd5afb4b7.png)

Hopefully this is what you had in mind!
