### ISSUE TITLE
Allow output of anchored comments to a file (.txt or .JSON)

### ISSUE THREAD

**Issue by FelipeTJ** [StarlaneStudios/vscode-comment-anchors#154]
It would be great if there was a functionality to output all of (or by filters if you want to get fancy) the commented anchors to a file. For example:

![Screenshot from 2022-05-17 17-12-43](https://user-images.githubusercontent.com/81302756/168831998-6818475e-7b54-4e5c-9b9a-72c5cb2888d2.png)

This window's text could just be output raw to a file.

**Comment by macjuul** [comment]
Thanks for the suggestion! A new command to export to CSV (Excel sheet) and JSON will be available in the next version.
