### ISSUE TITLE
Possible to Allow link tags to contain text regarding what the link is for?

### ISSUE THREAD

**Issue by DDIncNick** [StarlaneStudios/vscode-comment-anchors#156]
I have tried doing several different things with link tags all being unsuccessful.
```
//LINK Create Error Message : ./file.js:139
//LINK Create Error Message - ./file.js:139
//LINK ./file.js:139
```

Only the last works. If its possible or I am just doing it wrong, I would really like to be able to include a message with the link tag to avoid just cluttering the document with ```//NOTE``` tags or some other tag above it.

**Comment by macjuul** [comment]
Currently link anchors can only contain a link, no further text. Adding in support for additional text would be difficult considering a separator character could very well appear in the file path or anchor id, making it difficult to write a reliable regular expression for it.

The recommended approach currently is to add a second anchor. Sorry for the inconvenience!
