### ISSUE TITLE
manual on how to use vscode comment anchors

### ISSUE THREAD

**Issue by boris2024** [StarlaneStudios/vscode-comment-anchors#158]
dear Sirs,
I hope this message finds you well.

I'm new to vscode and programmig in general. I have read the description of your extension for vs code and it sounds ideal, being able to highlight code by changing the font color will be very useful.

I have tried looking for a manual to learn how to use your extension, but haven't found one that I can use (sorry)

is this available anywhere?
please, let me know,

thank you,

alvaro

**Comment by LucasFA** [comment]
In short, write TODO, or REVIEW, or LINK, or any of the available tags and it will be highlighted.

This extension doesn't highlight any other code, though, just the tags.

**Comment by macjuul** [comment]
Hello! My apologies for the late response.

While there is no manual, this repositories readme file explains all features and functionality of Comment Anchors
https://github.com/StarlaneStudios/vscode-comment-anchors/blob/master/README.md

If you believe something is missing feel free to open a separate issue.
