### ISSUE TITLE
Default anchors are not colored

### ISSUE THREAD

**Issue by altuga** [StarlaneStudios/vscode-comment-anchors#161]
Hello

vs code version : 1.68.1

settings.json 

{
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "editor.renderWhitespace": "none",
    "editor.renderControlCharacters": false,
    "files.autoSave": "afterDelay",
    "editor.unicodeHighlight.allowedLocales": {
      "_os": false,
      "_vscode": false,
      "tr": false
    },
    "breadcrumbs.enabled": false,
    "editor.unicodeHighlight.includeStrings": false,
    "editor.unicodeHighlight.ambiguousCharacters": false,
    "editor.selectionHighlight": false,
    "commentAnchors.tags.list": [
  
      {
        "tag": "ANCHOR",
        "iconColor": "default",
        "highlightColor": "#A8C023",
        "scope": "file"
      },
      {
        "tag": "TODO",
        "iconColor": "blue",
        "highlightColor": "#3ea8ff",
        "scope": "workspace"
      },
      {
        "tag": "FIXME",
        "iconColor": "red",
        "highlightColor": "#F44336",
        "scope": "workspace"
      },
      {
        "tag": "STUB",
        "iconColor": "purple",
        "highlightColor": "#BA68C8",
        "scope": "file"
      },
      {
        "tag": "NOTE",
        "iconColor": "orange",
        "highlightColor": "#FFB300",
        "scope": "file"
      },
      {
        "tag": "REVIEW",
        "iconColor": "green",
        "highlightColor": "#64DD17",
        "scope": "workspace"
      },
      {
        "tag": "SECTION",
        "iconColor": "blurple",
        "highlightColor": "#896afc",
        "scope": "workspace",
        "behavior": "region"
      },
      {
        "tag": "LINK",
        "iconColor": "#2ecc71",
        "highlightColor": "#2ecc71",
        "scope": "workspace",
        "behavior": "link"
      }
    ]
  }
      

I can see ANCHOR anchor in color in *.md files. 
This problem occurs after VS update.
Any suggestions?

**Comment by JordanDi123** [comment]
Hello,

Sorry to hear you are having problems! There is another issue, #172 that sounds similar to this one. If you are still having issues please see the most recent from me there and follow the steps produced so we can investigate further.

Thank you!
