### ISSUE TITLE
ANCHOR #id should be treated as current file

### ISSUE THREAD

**Issue by netizen-ais** [StarlaneStudios/vscode-comment-anchors#163]
Just like HTML anchors, shouldn't it?

**Comment by macjuul** [comment]
The anchors use a different syntax from HTML. You can however achieve the same behavior with [Link Anchors](https://github.com/StarlaneStudios/vscode-comment-anchors#link-anchors).

**Comment by netizen-ais** [comment]
That was my request. In a large file, with lot of anchors, I'm forced to type the file name in every // link

**Comment by macjuul** [comment]
Good point, I'll see if I can improve the workflow of linking within the same file
