### ISSUE TITLE
Update v1.10.0 change overriding default Opt-Shift-Up/Down vscode shortcut

### ISSUE THREAD

**Issue by leechongren** [StarlaneStudios/vscode-comment-anchors#166]
The new changes pertaining to #27 is overriding the default vscode shortcut to duplicate lines:
`Added keyboard navigation (Shift+Alt+Up & Shift+Alt+Down) (https://github.com/StarlaneStudios/vscode-comment-anchors/issues/27)`

Can we have a different shortcut for this functionality?

**Comment by macjuul** [comment]
Hey! This is a known issue and is currently being discussed in #157

I'll leave this issue open for any other people experiencing the same problem

**Comment by macjuul** [comment]
Version 1.10.1 has been released changing the default keybinds to `Alt + PageUp` and `Alt + PageDown`.
