### ISSUE TITLE
Feat : Highlight keys regardless of their position in a comment

### ISSUE THREAD

**Issue by aleportillo** [StarlaneStudios/vscode-comment-anchors#168]
In previous versions the word was highlighted when I wrote it like this
`// ------ ANCHOR : `

but in the new versions it is only highlighted if I write them like this
`// ANCHOR : `

I wish there was an option to enable the first highlight option, thank you!

**Comment by macjuul** [comment]
Hey, sorry for the inconvenience. We recently released a change to the anchor parser making it more strict. You can however specify custom anchor prefixes using the `commentAnchors.tags.matchPrefix`.

![image](https://user-images.githubusercontent.com/7606171/197164161-fcd58199-3a28-4497-ba2c-c12acf869b3e.png)

**Comment by aleportillo** [comment]
Thanks! That works for me.So, if you want you can close the issue ✨
