### ISSUE TITLE
Time for IntelliSense suggestions to appear

### ISSUE THREAD

**Issue by morallys** [StarlaneStudios/vscode-comment-anchors#174]
Time for IntelliSense suggestions to appear

I did some research on this issue which has been bothering me a lot lately. The default for the appearance of Comment Anchors suggestions should be double slashes, however, when inserting only one slash, the popup appears on top of the text unnecessarily. I already did the global configuration of IntelliSense and it worked, but only for the other functions of IntelliSense, for Comment Anchors it doesn't work.

I already tried using the configuration that is shown in the documentation:
  - global setting: "editor.quickSuggestionsDelay": 1000,

  - CommentAnchors setting: "commentAnchors.parseDelay": 5000

And even with 5000ms of delay, it appears automatically disturbing the development. Even in the source code control area the suggestion is appearing, only the one from CommentAnchors, the others from IntelliSensi do not appear, such as constants, functions, etc.

How can I fix this problem?

![image](https://user-images.githubusercontent.com/44041037/206939970-e79bfdcb-ccc9-47a5-83eb-c3cdc749cbe4.png)

![image](https://user-images.githubusercontent.com/44041037/206940283-1d667e25-4079-49d2-96d8-84555fa88143.png)

From the items below, IntelliSense should appear, not with just a slash:

![image](https://user-images.githubusercontent.com/44041037/206940568-ebabb321-c42a-4e96-9433-d87194339878.png)

**Comment by JordanDi123** [comment]
Hello,

I have fixed this issue and we are planning to release in an official version in the near future. If you would like you can clone main branch and build the extension on your own. :)

Thanks for reporting it!
