### ISSUE TITLE
Double Feature Request: Link to line number within same file and relative path to file

### ISSUE THREAD

**Issue by NazCodeland** [StarlaneStudios/vscode-comment-anchors#177]
Hey, this extension is awesome, thank you for making it. I see there are a insane amount of feature requests, I'm going to add two more to that :D. Whenever the day comes, it would be great if I can link to a comment/line-number within the same file and also being able to specify a file path relatively from where you are making the comment.

Thanks in advance.

**Comment by JordanDi123** [comment]
Hi!

I believe this feature is already existing through the use of the LINK anchor. Please read [this section](https://github.com/StarlaneStudios/vscode-comment-anchors#linking-to-a-specific-anchor) of the readme. 

Glad you are enjoying the extension and thank you for the kind words! :)
