### ISSUE TITLE
Styling in LINK overflows into next line

### ISSUE THREAD

**Issue by netizen-ais** [StarlaneStudios/vscode-comment-anchors#178]
![image](https://user-images.githubusercontent.com/3426685/214626135-99525b42-0f1c-43c0-b233-c59879ca769f.png)

**Comment by JordanDi123** [comment]
Hello,

Thank you for reporting this! 

I did some experimenting and in every case that I tried to reproduce this issue I couldn't figure out how to get the document link underline to display for more than a few seconds as it would quickly re-parse, correcting the issue on its own. I'm not sure if that is also the case for you or if the underline is sticking and not automatically reparsing to correct itself but I would be more than happy to take another look if you could give some steps to reproduce it.

Thank you for using comment anchors! :)

**Comment by netizen-ais** [comment]
hi. it's sticky, but I've just done some more research.
![image](https://user-images.githubusercontent.com/3426685/225898175-1c0840d3-2de2-4a6e-b99c-fa85f7dfd01b.png)
I've just cloned this repo and searched for detected-link (class shown in dev tools), and couldn't find it, also the underline comes from a css inside vscode, not your extension. Thank you and forgive me for the time you've lost because of this. I'll see if I file a bug report on vscode's repo now or just live with the dirty hack of and empty line bellow the link, that also fixes the bug

**Comment by netizen-ais** [comment]
Oh, it doesn't hapen with this extension disabled :(
