### ISSUE TITLE
snippets Only after adding the comment prefix

### ISSUE THREAD

**Issue by Mohammadev82** [StarlaneStudios/vscode-comment-anchors#180]
Hi,Thanks for you❤️
Please disable the snippets before adding comment
![image](https://user-images.githubusercontent.com/105316207/215396110-1dc0aa7c-625a-4d78-86ea-0cbd526a1ace.png)

**Comment by JordanDi123** [comment]
This is very similar to #39 but I see the slight difference between completely disabling the IntelliSense and then only showing when a prefix is provided. I'll look into this at some point. :)

Thanks for your support!
