### ISSUE TITLE
how disable file anchors badge

### ISSUE THREAD

**Issue by synhi** [StarlaneStudios/vscode-comment-anchors#189]
when i see the file anchors badge, i always want to click it, how disable the file anchors badge?

**Comment by macjuul** [comment]
VSCode has native functionality built in to disable this badge, simply right click the anchor icon and hit "Hide Badge". Hope that helps!

**Comment by synhi** [comment]
> VSCode has native functionality built in to disable this badge, simply right click the anchor icon and hit "Hide Badge". Hope that helps!

It's useful, thanks!
