### ISSUE TITLE
Is it a bug if section is not collapsible?

### ISSUE THREAD

**Issue by a5520614000** [StarlaneStudios/vscode-comment-anchors#196]
When I'm using section, it can't trigger the region function for code folding.
<img width="363" alt="1686801037127" src="https://github.com/StarlaneStudios/vscode-comment-anchors/assets/31464807/a7b89d74-4931-4dce-bfc8-a40a29298f4a">

**Comment by Zodsmar** [comment]
https://github.com/StarlaneStudios/vscode-comment-anchors/issues/75#issuecomment-629679105 

This feature was removed for various reasons.

**Comment by macjuul** [comment]
Following up on @Zodsmar comment, as it has been a few years since I removed folding I gave it another attempt, however it appears VSCode still displays the same broken behavior as it did before, so unfortunately it will still not be possible to implement this functionality.
