### ISSUE TITLE
[Color] Can't change default keyword gutter icon color

### ISSUE THREAD

**Issue by LatenPath** [StarlaneStudios/vscode-comment-anchors#211]
With default keyword like FIXME, NOTE,... When i change `highlightColor` 
![image](https://github.com/StarlaneStudios/vscode-comment-anchors/assets/145383056/cc54494d-3b1f-4073-954b-f1bfae80aab7)
Color has changed but the gutter DIDN'T.
![image](https://github.com/StarlaneStudios/vscode-comment-anchors/assets/145383056/664a2b00-2ad9-456e-b343-f117fd3d3e64)
Then i set `iconColor` to `default`.
![image](https://github.com/StarlaneStudios/vscode-comment-anchors/assets/145383056/301b531b-dded-46f5-a63a-e3ebdd9f7910)
The color changed but not match with the `highlightColor` setting.
![image](https://github.com/StarlaneStudios/vscode-comment-anchors/assets/145383056/3a9673fc-b557-42f0-888c-de4e1bd8bb15)

**Comment by Zodsmar** [comment]
You got like 80% of the way there. The Gutter color won't change unless you use "iconColor" which you got correct however using "default" is the default Anchor color (AKA white). So what you said is for the icon color to be White.

IconColor can take a HEX Code as well. Try putting your highlightColor into iconColor as well and it will work! 

It works for me. If this answers your question please close the ticket.

**Comment by LatenPath** [comment]
I didnt know that we can put hex code to that field. Thank you so much sir!
