### ISSUE TITLE
Feature Request: Strikethrough, Underline and Custom Style Tag

### ISSUE THREAD

**Issue by Zodsmar** [StarlaneStudios/vscode-comment-anchors#215]
I would love to see the JSON have the ability to have:
`"isStrikethrough": true,
      "isUnderline": true,`
      
Edit: PR was created which gives text decoration styling instead of booleans for it!
      
~~The custom style tag would be for allow just any CSS Style in it. By looking at the code I see that the tag itself is just converted to HTML so why not just have a customStyle tag that allows the users to add there own custom css styling!~~

**Comment by macjuul** [comment]
Closing as completed
