### ISSUE TITLE
navigation shortcuts

### ISSUE THREAD

**Issue by nilslindemann** [StarlaneStudios/vscode-comment-anchors#27]
When in editor, can we have navigation shortcuts like alt+up and alt+down?

Further, here is some inspiration, in case you want to become the coolest guy in town :-)

[Codebrowser](https://web.archive.org/web/20160912162221/http://tibleiz.net:80/code-browser/download.html) (use v. 4.9, later versions dont support relative indentation)

One can navigate _into_ Sections using alt+right/left!

**Comment by heronils** [comment]
My current workaround is to install the Block Travel plugin (currently v 0.0.2, it is small, two code files) and replace its _block.js_ with the attached one (please change the extension from _.txt_ to _.js_).

It works only for python style comments, if you want more functionality, tweak the _isComment_ function in that file according to your needs.

[blocks.txt](https://github.com/ExodiusStudios/vscode-comment-anchors/files/2626822/blocks.txt)

**Comment by mig8447** [comment]
I'd also love to see this

**Comment by dragonitaq** [comment]
I also feel there is a need to have some sort of shortcut navigation especially when you have large & long codes. I use ANCHOR, FIXME & TODO a lot. Wish there are ways to navigate. At least have the option to focus the comment anchor sidebar, and then we can use keyboard to navigate from there then switch back to editor, all done by shortcuts. I really wish this come true.

**Comment by macjuul** [comment]
My apologies for the long wait, I've finally had time to implement this functionality and it will be available in the next release.
