### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by dc-avasilev** [StarlaneStudios/vscode-comment-anchors#43]
- Issue Type: `Performance`
- Extension Name: `comment-anchors`
- Extension Version: `1.6.1`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

[ExodiusStudios.comment-anchors-unresponsive.cpuprofile.txt](https://pastebin.com/Hs84M4Dx)

**Comment by babakks** [comment]
This may help:
https://github.com/ExodiusStudios/vscode-comment-anchors/issues/8
