### ISSUE TITLE
Cannot Configire Anchor Tags

### ISSUE THREAD

**Issue by dyllandry** [StarlaneStudios/vscode-comment-anchors#44]
I edited my settings.json file to alter the SECTION tag's scope to just the file.
```
"commentAnchors.tags": [
        {
            "tag": "SECTION",
            "scope": "file",
        }
    ]
```
Now the SECTION anchor has lost all styling, though still appears in the Workspace Anchors search.
Changing the JSON in an attempt to restore lost styling affects nothing.
```
"commentAnchors.tags": [
        {
            "tag": "SECTION",
            "scope": "file",
            "iconColor": "red",
            "highlightColor": "#A8C023",
            "styleComment": true,
            "isItalic": true,
            "isBold": true,
            "enabled": true,
        }
    ]
```

**Comment by edgrim** [comment]
I solved this using `"commentAnchors.tags.list"` instead of `"commentAnchors.tags"` (which is not pointing at anything, apparently).
