### ISSUE TITLE
The icon's color become the former icon's color

### ISSUE THREAD

**Issue by hyj1116** [StarlaneStudios/vscode-comment-anchors#46]
After setting some configuration for the CommentAnchor extension, the icon's color becomes the former icon's color.

You can find the snapshot as the following URL: https://imgur.com/XrBpoiR

My setting is as follows:

     "commentAnchors.tags.list": [{
            "tag": "ANCHOR",
            "iconColor": "default",
            "highlightColor": "#A8C023",
            "scope": "file",
            "styleComment": true,
            "borderStyle": "1px solid #A8C023",
            "borderRadius": 5
            // "backgroundColor": "#49511d"
        },
        {
            "tag": "TODO",
            "iconColor": "blue",
            "highlightColor": "#3ea8ff",
            "scope": "workspace",
            "styleComment": true,
            "borderStyle": "1px solid #23b2ea",
            "borderRadius": 5
        },
        {
            "tag": "FIXME",
            "iconColor": "red",
            "highlightColor": "#F44336",
            "scope": "workspace",
            "styleComment": true,
            "borderStyle": "1px solid #F44336",
            "borderRadius": 5
        },
        {
            "tag": "STUB",
            "iconColor": "purple",
            "highlightColor": "#BA68C8",
            "scope": "file",
            "styleComment": true,
            "borderStyle": "1px solid #BA68C8",
            "borderRadius": 5
        },
        {
            "tag": "NOTE",
            "iconColor": "orange",
            "highlightColor": "#FFB300",
            "scope": "file",
            "styleComment": true,
            "borderStyle": "1px solid #FFB300",
            "borderRadius": 5
        },
        {
            "tag": "REVIEW",
            "iconColor": "green",
            "highlightColor": "#64DD17",
            "scope": "workspace",
            "styleComment": true,
            "borderStyle": "1px solid #64DD17",
            "borderRadius": 5
        },
        {
            "tag": "SECTION",
            "iconColor": "blurple",
            "highlightColor": "#896afc",
            "scope": "workspace",
            "isRegion": true,
            "styleComment": true,
            "borderStyle": "1px solid #896afc",
            "borderRadius": 5
        },
        {
            "tag": "TEST",
            "iconColor": "yellow",
            "highlightColor": "#f4d13d",
            "scope": "workspace",
            "isRegion": true,
            "styleComment": true,
            "borderStyle": "1px solid #f4d13d",
            "borderRadius": 5
        },
        {
            "tag": "PINK",
            "iconColor": "pink",
            "highlightColor": "#e84393",
            "scope": "workspace",
            "isRegion": true,
            "styleComment": true,
            "borderStyle": "1px solid #e84393",
            "borderRadius": 5
        },
        {
            "tag": "EMERALD",
            "iconColor": "emerald",
            "highlightColor": "#2ecc71",
            "scope": "workspace",
            "isRegion": true,
            "styleComment": true,
            "borderStyle": "1px solid #2ecc71",
            "borderRadius": 5
        },
        {
            "tag": "TEAL",
            "iconColor": "teal",
            "highlightColor": "#00cec9",
            "scope": "workspace",
            "isRegion": true,
            "styleComment": true,
            "borderStyle": "1px solid #00cec9",
            "borderRadius": 5
        }
    ]

How to normally display the icon's color as the succeeding anchor's color?

**Comment by JordanDi123** [comment]
I understand this is an older issue but I attempted to reproduce in the latest version (v1.9.3) using the same configuration but it appears to work as correctly. Can this be reproduced?

![image](https://user-images.githubusercontent.com/24500399/118418603-06736c80-b687-11eb-92b1-b4c358b548e1.png)
