### ISSUE TITLE
Feature request: I want Tag name shows on/off option.

### ISSUE THREAD

**Issue by newro** [StarlaneStudios/vscode-comment-anchors#47]
![image](https://user-images.githubusercontent.com/2032376/55455187-a42d8e00-561d-11e9-8657-85315226bd1e.png)

FILE ANCHORS nav bar shows tag name.
And I want to recognize what the comment means on nav bar.
But I was used to small width nav bar. So, there are only to showing tag name.
If you make option with tag name on/off, I will recognize comment on short width nav bar.

**Comment by lrosenthol** [comment]
I have the exact same request!  I can tell what the type is from the color of the icon, so I don't need the text...
