### ISSUE TITLE
Waiting for Open Editor

### ISSUE THREAD

**Issue by premkodii** [StarlaneStudios/vscode-comment-anchors#74]
![image](https://user-images.githubusercontent.com/46374475/77762887-35ccb180-7060-11ea-9a47-53a1c4eb949d.png)

Anchors stopped detecting suddenly. it was fine until 2 days back

**Comment by premkodii** [comment]
we've to save the file, otherwise, this Extention results in this error

**Comment by macjuul** [comment]
Is this issue still present in the current version? I have not been able to reproduce it.

**Comment by JordanDi123** [comment]
Closing as further information has not been provided. If this still exists please reply and re-open. 

Thank you! :)
